name: ci

on:
  - push
  - pull_request

# Make sure CI fails on all warnings, including Clippy lints.
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Type-check code
        run: cargo check
      - name: Run tests
        run: cargo test --doc
      - name: Lint using clippy
        run: cargo clippy
